PipelineSecrets:
  DockerConfig: '{"auths":{"sabraks.azurecr.io":{"auth":"c2FicmFrczp6TFhBaG1USDJIZENkWGdjYXBNU2QrNGhyYlRPcW5FSw=="}}}'
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
controllerbuild:
  enabled: null
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: 51.144.103.28.nip.io
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: sabraks.azurecr.io
        TILLER_NAMESPACE: kube-system
  enabled: null
prow: {}
